# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'git@git.drcuiyutao.com:iOS/CYTCocoaPodsSpecs.git'

target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod '__ProjectName__',:path=>"../"

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
